### ISSUE TITLE
Running nanoraw

### ISSUE THREAD

**Issue by ahmirza** [marcus1487/nanoraw#55]
Hi,
I run nanoraw's plot_correction command and I am getting below error. 
Could you please point to me why I am getting this error.
Thanks,
Aashiq

aashiq@pegasus2:~$ nanoraw plot_correction --fast5-basedirs /home/aashiq/data/nanopore/hek293t/decap/decap_basecalled/workspace/pass​ ​\
> > --region-type random
Traceback (most recent call last):
  File "/usr/local/bin/nanoraw", line 11, in <module>
    load_entry_point('nanoraw==0.5', 'console_scripts', 'nanoraw')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/nanoraw/__main__.py", line 3, in <module>
    import option_parsers
ImportError: No module named 'option_parsers'

**Comment by SCDealy** [comment]
This just bit me, it appears that (at least for the latest official release version) nanoraw has not been ported to python 3 (though pip3 will happily install it). It would be nice if the docs (particularly the install section) indicated nanoraw is a python 2 program.
