### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by lfaino** [marcus1487/nanoraw#58]
Dear Dev,
i get an error when i run `pip3 install nanoraw[plot] --user` 

here the error

Traceback (most recent call last):
  File "/home/instancelf/.local/bin/nanoraw", line 7, in <module>
    from nanoraw.__main__ import main
  File "/home/instancelf/.local/lib/python3.5/site-packages/nanoraw/__main__.py", line 3, in <module>
    import option_parsers
ImportError: No module named 'option_parsers'

**Comment by lfaino** [comment]
here another error when i use pip:

instancelf@instancelf:~/nanoporeData$ pip install nanoraw[plot] --user  --no-cache-dir
Collecting nanoraw[plot]
  Downloading https://files.pythonhosted.org/packages/a2/8c/4c30e9d9bfef5de2e299c6d304ddfe339ad24b7f4ce4e78fdd509d6b6f0e/nanoraw-0.5.tar.gz (50kB)
    100% |████████████████████████████████| 51kB 4.8MB/s
Collecting h5py (from nanoraw[plot])
  Downloading https://files.pythonhosted.org/packages/33/0c/1c5dfa85e05052aa5f50969d87c67a2128dc39a6f8ce459a503717e56bd0/h5py-2.8.0-cp27-cp27mu-manylinux1_x86_64.whl (2.7MB)
    100% |████████████████████████████████| 2.7MB 22.1MB/s
Collecting numpy (from nanoraw[plot])
  Downloading https://files.pythonhosted.org/packages/40/c5/f1ed15dd931d6667b40f1ab1c2fe1f26805fc2b6c3e25e45664f838de9d0/numpy-1.15.2-cp27-cp27mu-manylinux1_x86_64.whl (13.8MB)
    100% |████████████████████████████████| 13.8MB 25.8MB/s
Collecting scipy (from nanoraw[plot])
  Downloading https://files.pythonhosted.org/packages/2a/f3/de9c1bd16311982711209edaa8c6caa962db30ebb6a8cc6f1dcd2d3ef616/scipy-1.1.0-cp27-cp27mu-manylinux1_x86_64.whl (30.8MB)
    100% |████████████████████████████████| 30.8MB 21.0MB/s
Collecting rpy2 (from nanoraw[plot])
  Downloading https://files.pythonhosted.org/packages/f1/98/c7652cc9d7fc0afce74d2c30a52b9c9ac391713a63d037e4ab8feb56c530/rpy2-2.9.4.tar.gz (194kB)
    100% |████████████████████████████████| 204kB 30.5MB/s
    Complete output from command python setup.py egg_info:
    rpy2 is no longer supporting Python < 3. Consider using an older rpy2 release when using an older Python release.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-AL0fkM/rpy2/
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
